#!/usr/bin/env python

from io import BytesIO
from picamera import PiCamera
from time import sleep
import datetime
import os
import keyboard
from gpiozero import Button
import RPi.GPIO as GPIO
import time


camera = PiCamera()
Record = Button(2)
Record.when_pressed = camera.stop_preview
            


print ("  Press Ctrl & C to Quit")

class Camera:
    
    def __init__(self):
        '''Initial Settings'''
        
        #camera.overlays = '/home/zine.png/
        #camera.quality = (20000000)
        camera.image_effect = "film"
        camera.resolution = (1296,730)
        camera.framerate = (24)
        camera.exposure_compensation = (0)
        #camera.range = "high"
        camera.iso = (100)
        camera.shutter_speed =(48000)
        #camera.digital_gain = (70)
        camera.awb_mode = 'off'
        camera.awb_gains = (1.4)
        camera.contrast = (1)
        camera.sharpness = (0)
        camera.saturation = (-50)
        
    
        
        
        self.setPath()
        
    def setPath(self):
        '''Target Path to Save Video Towards'''

        rootPath = '/home/pi/Documents/Video/'
        timing = datetime.datetime.now().strftime('%Y-%m-%d%H%M%S')
        ext = '.mjpg'
        #quality ='1'
        
        self.targetPath = '%s%s' % (os.path.join(rootPath,timing),ext)

        return self.targetPath
        
    def record(self):
        '''Actual Recording'''
        
        if not camera.recording:
            from time import sleep
            
            
            camera.start_recording(self.targetPath)
            GPIO.setmode(GPIO.BCM)
            GPIO.setwarnings(False)
            GPIO.setup(18,GPIO.OUT)
            GPIO.output(18,GPIO.HIGH)
            time.sleep(5)
            GPIO.output(18,GPIO.LOW)
          

         
            
            

        return True


    
         def detectKeys(self):
        '''Key Assignments'''
        
        if keyboard.is_pressed("1"):
            camera.iso=100
        if keyboard.is_pressed("4"):
            camera.iso=400
        if keyboard.is_pressed("8"):
            camera.iso=799
        if keyboard.is_pressed("q"):
           camera.stop_preview()
        if keyboard.is_pressed("r"):
            self.record()
        if keyboard.is_pressed("a"):
            if not camera.preview:
                camera.start_preview()

        return True
        
    def run(self):
        '''Runtime'''
        
        self.detectKeys()
              
        return True

if __name__ == '__main__':
    piCam = Camera()
    while True:
      piCam.run()

